# Generated by Django 3.0.4 on 2020-07-01 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tecnology',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
